import type { Candidate, CandidateExperience } from "@cvhelper/shared";

/** Escapes LaTeX special characters so arbitrary user text can't break compilation. */
function escapeLatex(value: string): string {
  return value
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function href(url: string, label: string): string {
  return `\\href{${url}}{${escapeLatex(label)}}`;
}

function dateRange(start: string, end: string): string {
  return [start, end].filter(Boolean).join(" -- ");
}

function groupByCompany(experience: CandidateExperience[]): CandidateExperience[][] {
  const groups: CandidateExperience[][] = [];
  const indexByCompany = new Map<string, number>();
  for (const entry of experience) {
    const key = entry.company.trim().toLowerCase();
    const existingIndex = indexByCompany.get(key);
    if (existingIndex !== undefined) {
      groups[existingIndex].push(entry);
    } else {
      indexByCompany.set(key, groups.length);
      groups.push([entry]);
    }
  }
  return groups;
}

function renderAchievements(achievements: string[]): string {
  if (achievements.length === 0) return "";
  const items = achievements.map((a) => `  \\item ${escapeLatex(a)}`).join("\n");
  return `\\begin{itemize}\n${items}\n\\end{itemize}`;
}

function renderExperienceGroup(group: CandidateExperience[]): string {
  const [first] = group;
  const header = `\\textbf{${escapeLatex(first.company)} -- ${escapeLatex(first.role)}} \\hfill \\textit{${dateRange(first.startDate, first.endDate)}}`;

  const description = first.description ? escapeLatex(first.description) : "";
  const hasProjects = group.length > 1 || group.some((entry) => entry.project.trim());

  if (!hasProjects) {
    const body = [description, renderAchievements(first.achievements)].filter(Boolean).join("\n\n");
    return [header, body].filter(Boolean).join("\n\n");
  }

  const projectItems = group
    .map((entry) => {
      const title = entry.project.trim() || entry.role;
      const nested = renderAchievements(entry.achievements);
      return `\\item \\textbf{${escapeLatex(title)}}\n${nested}`;
    })
    .join("\n\n");

  const body = [description, `\\begin{itemize}\n${projectItems}\n\\end{itemize}`].filter(Boolean).join("\n\n");
  return [header, body].filter(Boolean).join("\n\n");
}

const LATEX_PREAMBLE = `% =========================
% Harvard-style CV (LaTeX) — generated by CVHelper
% =========================

\\documentclass[12pt]{article}
\\hyphenpenalty=10000
\\exhyphenpenalty=10000
\\usepackage[margin=1in]{geometry}
\\usepackage[hidelinks]{hyperref}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\usepackage{tabularx}
\\usepackage{xcolor}
\\usepackage{setspace}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}

\\pagenumbering{gobble}
\\setstretch{1.05}
\\setlist[itemize]{noitemsep, topsep=2pt, leftmargin=18pt}
\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]
\\titlespacing*{\\section}{0pt}{10pt}{6pt}
\\newcommand{\\name}[1]{\\begin{center}\\Huge\\bfseries #1\\end{center}}
\\newcommand{\\contact}[1]{\\begin{center}\\small #1\\end{center}}
\\newcommand{\\role}[1]{\\begin{center}\\normalsize #1\\end{center}}

\\begin{document}`;

export function candidateToLatex(candidate: Candidate): string {
  const { personal } = candidate;
  const sections: string[] = [LATEX_PREAMBLE];

  sections.push(`% ---------- Header ----------`);
  sections.push(`\\name{${escapeLatex(personal.name || "Untitled candidate")}}`);
  if (personal.professionalTitle) sections.push(`\\role{${escapeLatex(personal.professionalTitle)}}`);

  const contactParts: string[] = [];
  if (personal.location) contactParts.push(escapeLatex(personal.location));
  if (personal.email) contactParts.push(href(`mailto:${personal.email}`, personal.email));
  if (personal.linkedin) contactParts.push(href(personal.linkedin, personal.linkedin));
  if (personal.github) contactParts.push(href(personal.github, personal.github));
  if (personal.website) contactParts.push(href(personal.website, personal.website));
  if (contactParts.length > 0) {
    sections.push(`\\contact{ ${contactParts.join(" \\,|\\, ")} }`);
  }

  if (candidate.summary) {
    sections.push(`% ---------- Summary ----------\n\\section*{Summary}\n${escapeLatex(candidate.summary)}`);
  }

  if (candidate.techStack.length > 0) {
    const stackLines = candidate.techStack.map((tech) => `\\textbar ${escapeLatex(tech)}`).join("\n");
    sections.push(`\\section*{Tech Stack}\n${stackLines}`);
  }

  if (candidate.experience.length > 0) {
    const groups = groupByCompany(candidate.experience);
    const groupsLatex = groups.map(renderExperienceGroup).join("\n\n");
    sections.push(`% ---------- Experience ----------\n\\section*{Professional Experience}\n\n${groupsLatex}`);
  }

  if (candidate.education.length > 0) {
    const educationLines = candidate.education
      .map((edu) => `\\textbf{${escapeLatex(edu.degree)}} \\hfill ${escapeLatex(edu.institution)} (${escapeLatex(edu.endDate)})`)
      .join("\n\n");
    sections.push(`% ---------- Education ----------\n\\section*{Education}\n\n${educationLines}`);
  }

  if (candidate.languages.length > 0) {
    const languagesLine = candidate.languages
      .map((lang) => `${escapeLatex(lang.language)} (${escapeLatex(lang.level)})`)
      .join(" \\,|\\, ");
    sections.push(`% ---------- Languages ----------\n\\section*{Languages}\n\n${languagesLine}`);
  }

  sections.push(`\\end{document}`);

  return sections.join("\n\n");
}
