import type { CandidateExperience, CandidateLink, CvTailoringInput } from "@cvhelper/shared";

/** Escapes LaTeX special characters so arbitrary user text can't break compilation. */
function escapeLatex(value: string): string {
  return value
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

function href(url: string, label: string): string {
  return `\\href{${url}}{${escapeLatex(label)}}`;
}

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const URL_PATTERN = /^https?:\/\//i;

/** Renders a link's value as a clickable mailto/https link when recognized, plain escaped text otherwise. */
function renderLinkValue(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return "";
  if (EMAIL_PATTERN.test(trimmed)) return href(`mailto:${trimmed}`, trimmed);
  if (URL_PATTERN.test(trimmed)) return href(trimmed, trimmed);
  return escapeLatex(trimmed);
}

function renderLinks(links: CandidateLink[]): string {
  return links
    .map((link) => renderLinkValue(link.value))
    .filter(Boolean)
    .join(" \\,|\\, ");
}

function dateRange(start: string, end: string): string {
  return [start, end].filter(Boolean).join(" -- ");
}

function renderAchievements(achievements: string[]): string {
  if (achievements.length === 0) return "";
  const items = achievements.map((a) => `  \\item ${escapeLatex(a)}`).join("\n");
  return `\\begin{itemize}\n${items}\n\\end{itemize}`;
}

function renderExperienceEntry(entry: CandidateExperience): string {
  const header = `\\textbf{${escapeLatex(entry.company)} -- ${escapeLatex(entry.role)}} \\hfill \\textit{${dateRange(entry.startDate, entry.endDate)}}`;
  const description = entry.description ? escapeLatex(entry.description) : "";

  if (entry.projects.length === 0) {
    const body = [description, renderAchievements(entry.achievements)].filter(Boolean).join("\n\n");
    return [header, body].filter(Boolean).join("\n\n");
  }

  const projectItems = entry.projects
    .map((project) => {
      const nested = renderAchievements(project.goals);
      return `\\item \\textbf{${escapeLatex(project.name)}}\n${nested}`;
    })
    .join("\n\n");

  const body = [description, `\\begin{itemize}\n${projectItems}\n\\end{itemize}`].filter(Boolean).join("\n\n");
  return [header, body].filter(Boolean).join("\n\n");
}

const LATEX_PREAMBLE = `% =========================
% Harvard-style CV (LaTeX) — generated by CVHelper
% =========================

\\documentclass[12pt]{article}
\\hyphenpenalty=10000
\\exhyphenpenalty=10000
\\usepackage[margin=1in]{geometry}
\\usepackage[hidelinks]{hyperref}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\usepackage{tabularx}
\\usepackage{xcolor}
\\usepackage{setspace}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}

\\pagenumbering{gobble}
\\setstretch{1.05}
\\setlist[itemize]{noitemsep, topsep=2pt, leftmargin=18pt}
\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]
\\titlespacing*{\\section}{0pt}{10pt}{6pt}
\\newcommand{\\name}[1]{\\begin{center}\\Huge\\bfseries #1\\end{center}}
\\newcommand{\\contact}[1]{\\begin{center}\\small #1\\end{center}}
\\newcommand{\\role}[1]{\\begin{center}\\normalsize #1\\end{center}}

\\begin{document}`;

export function candidateToLatex(candidate: CvTailoringInput): string {
  const { personal } = candidate;
  const sections: string[] = [LATEX_PREAMBLE];

  sections.push(`% ---------- Header ----------`);
  sections.push(`\\name{${escapeLatex(personal.name || "Untitled candidate")}}`);
  if (personal.professionalTitle) sections.push(`\\role{${escapeLatex(personal.professionalTitle)}}`);

  const contactLine = renderLinks(personal.links);
  if (contactLine) {
    sections.push(`\\contact{ ${contactLine} }`);
  }

  if (candidate.summary) {
    sections.push(`% ---------- Summary ----------\n\\section*{Summary}\n${escapeLatex(candidate.summary)}`);
  }

  if (candidate.techStack.length > 0) {
    const stackLines = candidate.techStack.map((tech) => `\\textbar ${escapeLatex(tech)}`).join("\n");
    sections.push(`\\section*{Tech Stack}\n${stackLines}`);
  }

  if (candidate.experience.length > 0) {
    const entriesLatex = candidate.experience.map(renderExperienceEntry).join("\n\n");
    sections.push(`% ---------- Experience ----------\n\\section*{Professional Experience}\n\n${entriesLatex}`);
  }

  if (candidate.education.length > 0) {
    const educationLines = candidate.education
      .map((edu) => `\\textbf{${escapeLatex(edu.degree)}} \\hfill ${escapeLatex(edu.institution)} (${escapeLatex(edu.endDate)})`)
      .join("\n\n");
    sections.push(`% ---------- Education ----------\n\\section*{Education}\n\n${educationLines}`);
  }

  if (candidate.languages.length > 0) {
    const languagesLine = candidate.languages
      .map((lang) => `${escapeLatex(lang.language)} (${escapeLatex(lang.level)})`)
      .join(" \\,|\\, ");
    sections.push(`% ---------- Languages ----------\n\\section*{Languages}\n\n${languagesLine}`);
  }

  sections.push(`\\end{document}`);

  return sections.join("\n\n");
}
